version: "3.9"

services:
  app:
    container_name: infusion-drop
    image: ghcr.io/afidzulinn/infusion-drop:main
    networks:
      - bridge
    volumes:
      - webapp-infusion-drop-vol:/app
    restart: on-failure

networks:
  bridge:
    external: true
volumes:
  webapp-infusion-drop-vol:
    name: webapp-infusion-drop-vol
